// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class WishlistDetail
{
    public int Id { get; set; }

    public int WishlistId { get; set; }

    public string Location { get; set; }

    public string Name { get; set; }

    public int? LocationCategoryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual LocationCategory LocationCategory { get; set; }

    public virtual ICollection<VoteOption> VoteOptions { get; set; } = new List<VoteOption>();

    public virtual Wishlist Wishlist { get; set; }
}