// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class LocationCategory
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Color { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<WishlistDetail> WishlistDetails { get; set; } = new List<WishlistDetail>();
}