// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IdentityJWT.Models;

public class User
{
    public int Id { get; set; }

    public string Name { get; set; } //NOT NULL UNIQUE

    public DateOnly? Birthday { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string GoogleId { get; set; }

    public string Photo { get; set; }

    public int? Gender { get; set; }

    public string Email { get; set; }//NOT NULL UNIQUE

    public string Phone { get; set; }//UNIQUE

    public string PasswordHash { get; set; }//NOT NULL 
}